DB_URL: 'jdbc:postgresql://localhost:5432/fix'
DB_USERNAME: 'postgres'
DB_PASSWORD: 'Qasaqayj7'
MAIL_USERNAME: 'yesset.assan@gmail.com'
MAIL_PASSWORD: 'tnvqyiriqnefkzwt'
MAIL_PORT: 587
MAIL_HOST: 'smtp.gmail.com'
