spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: OnlineShop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/d_online_shop
    username: postgres
    password: Qasaqayj7
  mail:
    host: smtp.gmail.com
    port: 587
    username: yesset.assan@gmail.com
    password: tnvqyiriqnefkzwt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db/main-data.xml
